<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="8" total="11" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="CRMN" duration-ms="163234" started-at="2012-08-14T19:04:32Z" finished-at="2012-08-14T19:07:15Z">
    <groups>
      <group name="a">
        <method signature="CSRjourney.A_custCreation()[pri:0, instance:ACS_CRMN.CSRjourney@16b13c7]" name="A_custCreation" class="ACS_CRMN.CSRjourney"/>
        <method signature="CSRjourney.B_custBankDetails()[pri:0, instance:ACS_CRMN.CSRjourney@16b13c7]" name="B_custBankDetails" class="ACS_CRMN.CSRjourney"/>
        <method signature="CSRjourney.C_CheckProfile()[pri:0, instance:ACS_CRMN.CSRjourney@16b13c7]" name="C_CheckProfile" class="ACS_CRMN.CSRjourney"/>
        <method signature="CSRjourney.D_CheckEntitlement()[pri:0, instance:ACS_CRMN.CSRjourney@16b13c7]" name="D_CheckEntitlement" class="ACS_CRMN.CSRjourney"/>
        <method signature="WebJourney.A_WebJourney1()[pri:0, instance:ACS_CRMN.WebJourney@1f42b49]" name="A_WebJourney1" class="ACS_CRMN.WebJourney"/>
        <method signature="WebJourney.B_CheckProfile()[pri:0, instance:ACS_CRMN.WebJourney@1f42b49]" name="B_CheckProfile" class="ACS_CRMN.WebJourney"/>
        <method signature="WebJourney.C_WebJourney2()[pri:0, instance:ACS_CRMN.WebJourney@1f42b49]" name="C_WebJourney2" class="ACS_CRMN.WebJourney"/>
        <method signature="WebJourney.D_CheckEntitlement()[pri:0, instance:ACS_CRMN.WebJourney@1f42b49]" name="D_CheckEntitlement" class="ACS_CRMN.WebJourney"/>
      </group> <!-- a -->
    </groups>
    <test name="Webjourney" duration-ms="163234" started-at="2012-08-14T19:04:32Z" finished-at="2012-08-14T19:07:15Z">
      <class name="ACS_CRMN.WebJourney">
        <test-method status="PASS" signature="setUp()[pri:0, instance:ACS_CRMN.WebJourney@1f42b49]" name="setUp" is-config="true" duration-ms="17997" started-at="2012-08-14T19:04:32Z" finished-at="2012-08-14T19:04:50Z">
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="A_WebJourney1()[pri:0, instance:ACS_CRMN.WebJourney@1f42b49]" name="A_WebJourney1" duration-ms="41712" started-at="2012-08-14T19:04:50Z" finished-at="2012-08-14T19:05:32Z">
        </test-method> <!-- A_WebJourney1 -->
        <test-method status="FAIL" signature="B_CheckProfile()[pri:0, instance:ACS_CRMN.WebJourney@1f42b49]" name="B_CheckProfile" duration-ms="6180" started-at="2012-08-14T19:05:32Z" finished-at="2012-08-14T19:05:38Z">
          <exception class="org.json.JSONException">
            <message>
              <![CDATA[A JSONObject text must begin with '{' at character 1]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.json.JSONException: A JSONObject text must begin with '{' at character 1
	at org.json.JSONTokener.syntaxError(JSONTokener.java:496)
	at org.json.JSONObject.<init>(JSONObject.java:180)
	at org.json.JSONObject.<init>(JSONObject.java:403)
	at ACS_CRMN.AcsCalls.custProfile(AcsCalls.java:23)
	at ACS_CRMN.WebJourney.B_CheckProfile(WebJourney.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.json.JSONException -->
        </test-method> <!-- B_CheckProfile -->
        <test-method status="PASS" signature="C_WebJourney2()[pri:0, instance:ACS_CRMN.WebJourney@1f42b49]" name="C_WebJourney2" duration-ms="11713" started-at="2012-08-14T19:05:38Z" finished-at="2012-08-14T19:05:50Z">
        </test-method> <!-- C_WebJourney2 -->
        <test-method status="FAIL" signature="D_CheckEntitlement()[pri:0, instance:ACS_CRMN.WebJourney@1f42b49]" name="D_CheckEntitlement" duration-ms="384" started-at="2012-08-14T19:05:50Z" finished-at="2012-08-14T19:05:50Z">
          <exception class="org.json.JSONException">
            <message>
              <![CDATA[A JSONObject text must begin with '{' at character 1]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.json.JSONException: A JSONObject text must begin with '{' at character 1
	at org.json.JSONTokener.syntaxError(JSONTokener.java:496)
	at org.json.JSONObject.<init>(JSONObject.java:180)
	at org.json.JSONObject.<init>(JSONObject.java:403)
	at ACS_CRMN.AcsCalls.custEntitlements(AcsCalls.java:55)
	at ACS_CRMN.WebJourney.D_CheckEntitlement(WebJourney.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.json.JSONException -->
        </test-method> <!-- D_CheckEntitlement -->
        <test-method status="PASS" signature="E_WebJourneyEdit()[pri:0, instance:ACS_CRMN.WebJourney@1f42b49]" name="E_WebJourneyEdit" duration-ms="53524" started-at="2012-08-14T19:05:50Z" finished-at="2012-08-14T19:06:43Z">
        </test-method> <!-- E_WebJourneyEdit -->
        <test-method status="FAIL" signature="F_checkProfile()[pri:0, instance:ACS_CRMN.WebJourney@1f42b49]" name="F_checkProfile" duration-ms="5195" started-at="2012-08-14T19:06:43Z" finished-at="2012-08-14T19:06:49Z">
          <exception class="org.json.JSONException">
            <message>
              <![CDATA[A JSONObject text must begin with '{' at character 1]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.json.JSONException: A JSONObject text must begin with '{' at character 1
	at org.json.JSONTokener.syntaxError(JSONTokener.java:496)
	at org.json.JSONObject.<init>(JSONObject.java:180)
	at org.json.JSONObject.<init>(JSONObject.java:403)
	at ACS_CRMN.AcsCalls.custProfile(AcsCalls.java:23)
	at ACS_CRMN.WebJourney.F_checkProfile(WebJourney.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.json.JSONException -->
        </test-method> <!-- F_checkProfile -->
        <test-method status="FAIL" signature="G_CheckEntitlement()[pri:0, instance:ACS_CRMN.WebJourney@1f42b49]" name="G_CheckEntitlement" duration-ms="153" started-at="2012-08-14T19:06:49Z" finished-at="2012-08-14T19:06:49Z">
          <exception class="org.json.JSONException">
            <message>
              <![CDATA[A JSONObject text must begin with '{' at character 1]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.json.JSONException: A JSONObject text must begin with '{' at character 1
	at org.json.JSONTokener.syntaxError(JSONTokener.java:496)
	at org.json.JSONObject.<init>(JSONObject.java:180)
	at org.json.JSONObject.<init>(JSONObject.java:403)
	at ACS_CRMN.AcsCalls.custEntitlements(AcsCalls.java:55)
	at ACS_CRMN.WebJourney.G_CheckEntitlement(WebJourney.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.json.JSONException -->
        </test-method> <!-- G_CheckEntitlement -->
      </class> <!-- ACS_CRMN.WebJourney -->
      <class name="ACS_CRMN.CSRjourney">
        <test-method status="PASS" signature="setUp()[pri:0, instance:ACS_CRMN.CSRjourney@16b13c7]" name="setUp" is-config="true" duration-ms="16073" started-at="2012-08-14T19:06:49Z" finished-at="2012-08-14T19:07:05Z">
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="A_custCreation()[pri:0, instance:ACS_CRMN.CSRjourney@16b13c7]" name="A_custCreation" duration-ms="0" started-at="2012-08-14T19:07:05Z" finished-at="2012-08-14T19:07:05Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at ACS_CRMN.CSRBaseClass.custCreation(CSRBaseClass.java:63)
	at ACS_CRMN.CSRjourney.A_custCreation(CSRjourney.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
        </test-method> <!-- A_custCreation -->
        <test-method status="FAIL" signature="B_custBankDetails()[pri:0, instance:ACS_CRMN.CSRjourney@16b13c7]" name="B_custBankDetails" duration-ms="1" started-at="2012-08-14T19:07:05Z" finished-at="2012-08-14T19:07:05Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at ACS_CRMN.CSRBaseClass.BankDetails(CSRBaseClass.java:114)
	at ACS_CRMN.CSRjourney.B_custBankDetails(CSRjourney.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
        </test-method> <!-- B_custBankDetails -->
        <test-method status="FAIL" signature="C_CheckProfile()[pri:0, instance:ACS_CRMN.CSRjourney@16b13c7]" name="C_CheckProfile" duration-ms="5157" started-at="2012-08-14T19:07:05Z" finished-at="2012-08-14T19:07:10Z">
          <exception class="org.json.JSONException">
            <message>
              <![CDATA[A JSONObject text must begin with '{' at character 1]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.json.JSONException: A JSONObject text must begin with '{' at character 1
	at org.json.JSONTokener.syntaxError(JSONTokener.java:496)
	at org.json.JSONObject.<init>(JSONObject.java:180)
	at org.json.JSONObject.<init>(JSONObject.java:403)
	at ACS_CRMN.AcsCalls.custProfile(AcsCalls.java:23)
	at ACS_CRMN.CSRjourney.C_CheckProfile(CSRjourney.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.json.JSONException -->
        </test-method> <!-- C_CheckProfile -->
        <test-method status="FAIL" signature="D_CheckEntitlement()[pri:0, instance:ACS_CRMN.CSRjourney@16b13c7]" name="D_CheckEntitlement" duration-ms="5127" started-at="2012-08-14T19:07:10Z" finished-at="2012-08-14T19:07:15Z">
          <exception class="org.json.JSONException">
            <message>
              <![CDATA[A JSONObject text must begin with '{' at character 1]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.json.JSONException: A JSONObject text must begin with '{' at character 1
	at org.json.JSONTokener.syntaxError(JSONTokener.java:496)
	at org.json.JSONObject.<init>(JSONObject.java:180)
	at org.json.JSONObject.<init>(JSONObject.java:403)
	at ACS_CRMN.AcsCalls.custEntitlements(AcsCalls.java:55)
	at ACS_CRMN.CSRjourney.D_CheckEntitlement(CSRjourney.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.json.JSONException -->
        </test-method> <!-- D_CheckEntitlement -->
      </class> <!-- ACS_CRMN.CSRjourney -->
    </test> <!-- Webjourney -->
  </suite> <!-- CRMN -->
</testng-results>
