<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="60182" started-at="2012-08-16T14:20:48Z" finished-at="2012-08-16T14:21:48Z">
    <groups>
      <group name="a">
        <method signature="TLSjourney.A_TLSwebJourney()[pri:0, instance:ACS_CRMN.TLSjourney@120a47e]" name="A_TLSwebJourney" class="ACS_CRMN.TLSjourney"/>
        <method signature="TLSjourney.B_TLScheckProfile()[pri:0, instance:ACS_CRMN.TLSjourney@120a47e]" name="B_TLScheckProfile" class="ACS_CRMN.TLSjourney"/>
        <method signature="TLSjourney.D_CheckEntitlement()[pri:0, instance:ACS_CRMN.TLSjourney@120a47e]" name="D_CheckEntitlement" class="ACS_CRMN.TLSjourney"/>
      </group> <!-- a -->
    </groups>
    <test name="Default test" duration-ms="60182" started-at="2012-08-16T14:20:48Z" finished-at="2012-08-16T14:21:48Z">
      <class name="ACS_CRMN.TLSjourney">
        <test-method status="PASS" signature="setUp()[pri:0, instance:ACS_CRMN.TLSjourney@120a47e]" name="setUp" is-config="true" duration-ms="20131" started-at="2012-08-16T14:20:48Z" finished-at="2012-08-16T14:21:08Z">
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="A_TLSwebJourney()[pri:0, instance:ACS_CRMN.TLSjourney@120a47e]" name="A_TLSwebJourney" duration-ms="28239" started-at="2012-08-16T14:21:08Z" finished-at="2012-08-16T14:21:36Z">
        </test-method> <!-- A_TLSwebJourney -->
        <test-method status="PASS" signature="B_TLScheckProfile()[pri:0, instance:ACS_CRMN.TLSjourney@120a47e]" name="B_TLScheckProfile" duration-ms="11471" started-at="2012-08-16T14:21:36Z" finished-at="2012-08-16T14:21:48Z">
        </test-method> <!-- B_TLScheckProfile -->
        <test-method status="FAIL" signature="D_CheckEntitlement()[pri:0, instance:ACS_CRMN.TLSjourney@120a47e]" name="D_CheckEntitlement" duration-ms="327" started-at="2012-08-16T14:21:48Z" finished-at="2012-08-16T14:21:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Entitlements  before updation...should be zero....... expected:<false> but was:<true>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Entitlements  before updation...should be zero....... expected:<false> but was:<true>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:281)
	at ACS_CRMN.TLSjourney.D_CheckEntitlement(TLSjourney.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
        </test-method> <!-- D_CheckEntitlement -->
      </class> <!-- ACS_CRMN.TLSjourney -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
